### ISSUE TITLE
Restart loop

### ISSUE THREAD

**Issue by Fabian7727** [gutweiler/homebridge-platform-deconz#4]
Hi, thanks for your plugin. 

everything worked fine for me until I installed pi-hole. now the homebridge service ist in a restart loop with following journalctl:

>Feb 11 12:20:01 kueche homebridge[1680]: [2019-2-11 12:20:01] Homebridge is running on port 51826.
>Feb 11 12:20:01 kueche homebridge[1680]: undefined:2
>Feb 11 12:20:01 kueche homebridge[1680]:     <html><head>
>Feb 11 12:20:01 kueche homebridge[1680]:     ^
>Feb 11 12:20:01 kueche homebridge[1680]: SyntaxError: Unexpected token < in JSON at position 5
>Feb 11 12:20:01 kueche homebridge[1680]:     at JSON.parse (<anonymous>)
>Feb 11 12:20:01 kueche homebridge[1680]:     at deconzPlatform.<anonymous> (/usr/lib/node_modules/homebridge-platform-deconz/index.js:62:35)
>Feb 11 12:20:01 kueche homebridge[1680]:     at Request.self.callback (/usr/lib/node_modules/homebridge-platform-deconz/node_modules/request/request.js:185:22)
>Feb 11 12:20:01 kueche homebridge[1680]:     at Request.emit (events.js:189:13)
>Feb 11 12:20:01 kueche homebridge[1680]:     at Request.<anonymous> (/usr/lib/node_modules/homebridge-platform-deconz/node_modules/request/request.js:1161:10)
>Feb 11 12:20:01 kueche homebridge[1680]:     at Request.emit (events.js:189:13)
>Feb 11 12:20:01 kueche homebridge[1680]:     at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-platform-deconz/node_modules/request/request.js:1083:12)
>Feb 11 12:20:01 kueche homebridge[1680]:     at Object.onceWrapper (events.js:277:13)
>Feb 11 12:20:01 kueche homebridge[1680]:     at IncomingMessage.emit (events.js:194:15)
>Feb 11 12:20:01 kueche homebridge[1680]:     at endReadableNT (_stream_readable.js:1103:12)
>Feb 11 12:20:01 kueche systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
>Feb 11 12:20:01 kueche systemd[1]: homebridge.service: Unit entered failed state.
>Feb 11 12:20:01 kueche systemd[1]: homebridge.service: Failed with result 'exit-code'.
>Feb 11 12:20:11 kueche systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
>Feb 11 12:20:11 kueche systemd[1]: Stopped Node.js HomeKit Server.

any idea on how to fix it?

**Comment by gutweiler** [comment]
Looks like the pi-hole service is now running on the port where the deconz-api is configured to run.
